import scala.util.Random

/**
 * The DiceEngine evaluates Abstract Syntax Trees generated by the DiceParser.
 * It delegates random generation to the Kalman Filter (EntropyFusionFilter).
 */
object DiceEngine {

  /**
   * Evaluates a dice expression string and calculates its statistical mean.
   *
   * @param expression The dice notation string to evaluate.
   * @param injectedKarma An external modifier generated by the Karma Controller.
   * @return A RollResult object containing the full breakdown.
   */
  def evaluate(expression: String, injectedKarma: Int = 0): RollResult = {
    // 1. Parse the string into an AST
    val astRoot = DiceParser.parse(expression)

    // 2. Recursively evaluate the AST
    val (rawTotal, individualRolls, keptRolls, expectedMean) = evaluateAST(astRoot)

    // 3. Apply external karma
    val finalTotal = rawTotal + injectedKarma

    // We pass exactly 6 arguments as defined in the updated Models.scala
    RollResult(
      expression,
      individualRolls,
      keptRolls,
      injectedKarma,
      expectedMean,
      finalTotal
    )
  }

  /**
   * Recursively traverses and evaluates an AST node.
   *
   * @return A tuple containing (Total Sum, List of Individual Rolls, List of Kept Rolls, Expected Mean).
   */
  private def evaluateAST(node: ASTNode): (Int, List[Int], List[Int], Double) = node match {
    case NumberNode(value) =>
      (value, Nil, Nil, value.toDouble)

    case DiceNode(quantity, sides, isExploding, keepConfig) =>
      if (sides < 1) throw new IllegalArgumentException("Dice must have at least one side.")
      if (sides < 2 && isExploding) throw new IllegalArgumentException("Cannot explode a 1-sided die.")

      val individual = (1 to quantity).toList.flatMap { _ =>
        if (isExploding) rollExploding(sides) else rollStandard(sides)
      }

      val keepAmount = keepConfig.map(_._2).getOrElse(individual.size)
      val kept = keepConfig.map(_._1) match {
        case Some("kh") => individual.sortBy(-_).take(keepAmount)
        case Some("kl") => individual.sorted.take(keepAmount)
        case _         => individual
      }

      val mean = quantity * (sides + 1) / 2.0
      (kept.sum, individual, kept, mean)

    case BinaryOpNode(left, op, right) =>
      val (lTotal, lInd, lKept, lMean) = evaluateAST(left)
      val (rTotal, rInd, rKept, rMean) = evaluateAST(right)

      val finalTotal = if (op == "+") lTotal + rTotal else lTotal - rTotal
      val finalMean = if (op == "+") lMean + rMean else lMean - rMean

      (finalTotal, lInd ++ rInd, lKept ++ rKept, finalMean)
  }

  // --- Random generation powered by Kalman Fusion Filter ---

  private def rollStandard(sides: Int): List[Int] = {
    List(EntropyFusionFilter.fuseRoll(sides))
  }

  private def rollExploding(sides: Int): List[Int] = {
    val roll = EntropyFusionFilter.fuseRoll(sides)
    if (roll == sides) roll :: rollExploding(sides)
    else List(roll)
  }
}
